# Generated by Django 2.2 on 2021-08-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quotee',
            field=models.CharField(max_length=255),
        ),
    ]
